tests for Sprint-4
TatyanaDevyatova/Sprint_4 pull request #1
Opened 2022-10-02 19:50 UTC by TatyanaDevyatova

2022-10-03 16:18 UTC, pavel-ulan requested changes
Работа клевая и ты молодец. Мне нравится общий подход и ряд решений. У тебя неплохо получается.
Есть ряд моментов которые так или иначе не подходят в решении данного задания. Посмотри комменты и поправь пожалуйста.
И еще. почитай, что коммитят в репозиторий, а что нет. Можешь это проследить по тому, какие файлы заносят в .gitignore обычно (можешь поискать шаблоны файлов, в интернете много примеров под каждый из типов проектов). Так например папку .idea и файлы iml в реп не коммитят.

2022-10-03 16:18 UTC, pavel-ulan commented on src/test/java/OrderScooterTests/OrderScooterTestInChrome.java
> +}
С одной стороны - задумка клевая 👍. С другой стороны, реализация через абстрактный класс скажем так - спорная. абстрактный класс подходит для построения расширяющих систем, где мы  абстрактной реализации приходим к конкретным системам. У тебя все уже есть, и единственный момент - передаваемый драйвер. Это не абстракция. Драйвер, это по сути просто конфигурация. Так что сюда больше подходит реализация создания драйвера через фабрику (шаблон проектирования) или банально можно задавать драйвер в конфиг файле.
Еще раз повторюсь, задумка клевая, просто тут она не совсем к месту. Но не останавливайся пробовать реализовывать разные подходы, это значительно лучше, чем этого не делать. =)

2022-10-03 16:18 UTC, pavel-ulan commented on src/test/java/QuestionsAboutImportantTests/QuestionsAboutImportantParametrizedTest.java
> +}
Я тебя прекрасно понимаю и сам согласен, что этот тест идеально подходит для параметризации. Но в условии сказано "Важно написать отдельный тест на каждый вопрос.", а работа с ТЗ это неотъемлемая часть работы инженера (и клево, если инженер внимательный =) ). Так что раскинь тест на каждый из вопросов.

2022-10-03 20:23 UTC, TatyanaDevyatova commented on src/test/java/QuestionsAboutImportantTests/QuestionsAboutImportantParametrizedTest.java
> +}
Тесты разделила

2022-10-03 20:24 UTC, TatyanaDevyatova commented on src/test/java/OrderScooterTests/OrderScooterTestInChrome.java
> +}
Заменила абстрактный класс с наследниками на фабрику

2022-10-04 12:31 UTC, pavel-ulan approved these changes
Клево 👍 
Получилось очень хорошо. Есть моменты для улучшения конечно и надеюсь ты будешь так же пробовать разные подходы.

2022-10-04 12:31 UTC, pavel-ulan commented on src/test/java/QuestionsAboutImportantTests/QuestionsAboutImportantTests.java
> +        driver = DriverFactory.getDriver(driverType);
Я бы наверное еще посоветовал вынести инициализацию драйвера куда-то из этого метода. а то как-то нелогично: метод вроде как assertation, но выполняет еще и утилитную функцию. Так не делают.

2022-10-04 12:31 UTC, pavel-ulan commented on .gitignore
> +# Compiled class file
Какой-то не тот ты gitignore взяла... это явно не для webapp автотестов =)
Но это лучше, чем совсем без него.

2022-10-08 10:27 UTC, merged